-- Generated by ChatGPt 4o
-- Jordank (jmynes)
--
-- This script takes a sprite with 32x32px frames, and centers it in 64x64px frames, without resizing the sprites

local spr = app.activeSprite
if not spr then
   app.alert("There is no active sprite.")
   return
end

local originalFrameSize = 32
local newFrameSize = 64

-- Calculate the new canvas dimensions based on the number of columns and rows in the original sprite
local columns = math.floor(spr.width / originalFrameSize)
local rows = math.floor(spr.height / originalFrameSize)
local newWidth = columns * newFrameSize
local newHeight = rows * newFrameSize

-- Create a new sprite with the new dimensions and the same color mode as the original
local newSprite = Sprite(newWidth, newHeight, spr.colorMode)

-- Limit the palette to the exact number of colors in the original palette
local originalPalette = spr.palettes[1]
newSprite:setPalette(originalPalette)

-- Copy each 32x32 region from the original sprite and draw it into the center of each 64x64 cell in the new sprite
for row = 0, rows - 1 do
   for col = 0, columns - 1 do
      local x = col * originalFrameSize
      local y = row * originalFrameSize
      local newX = col * newFrameSize + (newFrameSize - originalFrameSize) / 2
      local newY = row * newFrameSize + (newFrameSize - originalFrameSize) / 2

      -- Define the region to copy from the original sprite
      local region = Image(originalFrameSize, originalFrameSize, spr.colorMode)
      region:drawSprite(spr, 1, -x, -y) -- Draw the specific 32x32 section from original

      -- Use drawPixels to place the region in the center of the new 64x64 cell
      for px = 0, originalFrameSize - 1 do
         for py = 0, originalFrameSize - 1 do
            local color = region:getPixel(px, py)
            newSprite.cels[1].image:putPixel(newX + px, newY + py, color)
         end
      end
   end
end

app.activeSprite = newSprite
app.refresh()

